master:
  componentName: jenkins-master
  image: "jenkins/jenkins"
  tag: "2.162"
  imagePullPolicy: "Always"
  useSecurity: true
  adminUser: admin
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  servicePort: 8080
  serviceType: NodePort
  nodePort: 32000
  serviceAnnotations: {}
  containerPort: 8080
  healthProbesLivenessTimeout: 5
  healthProbesReadinessTimeout: 5
  healthProbeLivenessPeriodSeconds: 10
  healthProbeReadinessPeriodSeconds: 10
  healthProbeLivenessFailureThreshold: 5
  healthProbeReadinessFailureThreshold: 3
  healthProbeLivenessInitialDelay: 90
  healthProbeReadinessInitialDelay: 60
  slaveListenerPort: 50000
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  installPlugins:
    - kubernetes:1.14.3
    - workflow-aggregator:2.5
    - workflow-job:2.31
    - credentials-binding:1.17
    - git:3.9.3
    - git-client:2.7.6
    - greenballs:1.15
    - ws-cleanup:0.37
  scriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  customConfigMap: false
  nodeSelector: {}
  tolerations: {}

agent:
  enabled: true
  image: jenkins/jnlp-slave
  tag: 3.10-1
  componentName: "jenkins-slave"
  privileged: false
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  # You may want to change this to true while testing a new image
  alwaysPullImage: false
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
  nodeSelector: {}

persistence:
  enabled: true
  annotations: {}
  accessMode: ReadWriteOnce
  size: 20Gi
  volumes:
  #  - name: nothing
  #    emptyDir: {}
  mounts:
  #  - mountPath: /var/nothing
  #    name: nothing
  #    readOnly: true

networkPolicy:
  enabled: false
  apiVersion: networking.k8s.io/v1

rbac:
  create: true
  serviceAccount:
    name: default
  apiVersion: v1beta1
